tests fixed
sheinsvyatoslav/js-part-0 pull request #1
Opened 2022-12-15 15:06 UTC by sheinsvyatoslav

Missed code for tests was added

2022-12-18 23:33 UTC, ipetropolsky requested changes

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +  typeof a === "object" && typeof b === "object"
Ты наверно хотел сказать `Array.isArray`? )

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +    ? JSON.stringify(a) === JSON.stringify(b)
Принимается, т.к. с массивами примитивов будет работать. Но вообще опасно использовать `stringify` в таких делах, он не всегда выдаёт очевидный результат.
```js
areEqual([{}], [new Set([1,2])]) // true
areEqual([null], [NaN]) // true
```

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> -        console.log('');
Зачем ты всё переформатировал? Особенно при наличии линтера. Это лишний дифф, который усложняет ревью.

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +  new Set(getTypesOfItems(arr)).size === 1;
👍

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +  return Object.entries(obj);
👍

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +    .reduce((acc, item) => ({ ...acc, [item]: (acc[item] || 0) + 1 }), {});
Я бы не советовал в `reduce` использовать spread, сильно долго получается. Но для такой маленькой задачки сойдёт.

2022-12-18 23:33 UTC, ipetropolsky commented on index.js
> +  "set",
Добавишь несколько типов?

2022-12-19 19:43 UTC, sheinsvyatoslav commented on index.js
> +  typeof a === "object" && typeof b === "object"
нет, я так и хотел, чтоб работало еще и с объектами

2022-12-19 19:44 UTC, sheinsvyatoslav commented on index.js
> +    ? JSON.stringify(a) === JSON.stringify(b)
можно сделать доп. функцию isEqual, глубоко проверяющую объекты, но для этой задачи слишком длинно получается)

2022-12-19 19:44 UTC, sheinsvyatoslav commented on index.js
> -        console.log('');
вернул форматирование

2022-12-19 19:47 UTC, sheinsvyatoslav commented on index.js
> +    .reduce((acc, item) => ({ ...acc, [item]: (acc[item] || 0) + 1 }), {});
можно obj[item] ? obj[item]++ : (obj[item] = 1), но редьюсером тут короче и красивее получается(хотя и сложность больше). В задачах помассивне лучше конечно циклом и obj[item] ? obj[item]++ : (obj[item] = 1)

2022-12-19 20:22 UTC, ipetropolsky commented on index.js
> +    ? JSON.stringify(a) === JSON.stringify(b)
Да тут и не надо, достаточно массивов.

2022-12-19 20:24 UTC, ipetropolsky approved these changes

2022-12-19 20:29 UTC, ipetropolsky commented on index.js
> +    .reduce((acc, item) => ({ ...acc, [item]: (acc[item] || 0) + 1 }), {});
Да, только присвоение внутри тернарника лучше не делать. Вообще присвоение внутри выражения лучше не делать, оно не очень заметно так. Лучше написать `(obj[item] || 0) +1`.

2022-12-20 11:44 UTC, merged